### ISSUE TITLE
Question: How to do ajax requests?

### ISSUE THREAD

**Issue by osben** [Dirble/api-doc#11]
How to do ajax requests? 
Because we see
...'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://domain' is therefore not allowed access....

**Comment by confact** [comment]
Hi!

I am kinda negative to a CORS support because the api key will be seen by the client and then it can be misuse and make you as a developer by more when you hit the limit, if you pay for it or just not be abel to use the api when it hit the limit if you use the free plan.

Come with a good reason for me to support it and i will reconsider, but for now it will not be supported.
