### ISSUE TITLE
Retrieving information about the current song or if there is a song at the moment being played

### ISSUE THREAD

**Issue by farolfo** [Dirble/api-doc#3]
I have this question: Is there a way of knowing if a radio is actually playing a song at the moment with the API's data? I see you provide song_history but I don't know if it is being played at the moment.

Thanks !

**Comment by confact** [comment]
Hi @farolfo 

Sorry for a slow response. It is hard to group station songs based on station id to get the latest song played now. Due to it being a 25 million row mongodb. MongoDB hate grouping in a fast way.

It is also never 100% sure to know if the song is actually playing right now. The latest song in song_history shall in theory be the song playing last. But you can never be sure it is the latest due to updates from stream and so on.

You can take song_history and trust it for now. 

I plan to have recent played song endpoint so you can get latest play song for all stations on Dirble.

I hope that answers your question
