### ISSUE TITLE
Error code when you run out of requests?

### ISSUE THREAD

**Issue by adamcik** [Dirble/api-doc#8]
From the current docs:

> 401   Unauthorized – Your API token is wrong
> 429   Too Many Requests – You’re requesting too many stations! Slow down!

What error code will we get when the 1500 freebie plan queries run out? `402 Payment Required` might make sense?

**Comment by adamcik** [comment]
Though 402 is current `This code is reserved for future use.` according to RFC-2616.

On a quick side note, 401 "MUST include a WWW-Authenticate header field" according to the RFC, perhaps a 403 is more appropriate?

Though I'm not sure what the common practice is for mapping status codes in these types of APIs and how lenient they typically are relative to the HTTP RFC.

As long as I can detect that users have run out of quota and notify them I'll be happy :-)

**Comment by confact** [comment]
@adamcik sorry for late response. They will get 429 right now, because they do hit the rate limit.
But true, it is more or less a mix of 429 and 402. 

Right now many apis is sending status 401 without enforcing the header field. So it is a bit flexible in that sense. But sure, it is a lot of stuff i could do better on the API and it is getting better and better.

But you can use 429 for that for now. And it will only be triggered for those who use the free plan.

**Comment by adamcik** [comment]
Thanks for clarifying :-)
